### ISSUE TITLE
Question on Prediction Threshold in eval_int Function

### ISSUE THREAD

**Issue by zq8yx** [syleeheal/SAFETY#1]
Hello, I am currently studying your code and I came across the `eval_int` function in the `train/eval.py` file. I noticed that the prediction threshold for `int_pred` is set to 0.5, as shown in the following line of code:
```python
int_pred = (int_prob > 0.5).cpu().numpy().reshape(-1, int_prob.shape[-1])
```
I am curious as to why the threshold is set to 0.5, and why we are considering all values greater than 0.5 as the predicted intent. This seems to imply a multi-label classification approach, where an instance can belong to multiple classes. However, wouldn't it be more accurate to consider only the maximum value as the predicted intent for a multi-class classification problem? Could you please provide some insight into this design choice?
By the way, I am trying to replicate your experiment results but I am facing some difficulties. I suspect it might be due to the Python version I am using or other reasons. Could you please specify the Python version you used for this project?

**Comment by syleeheal** [comment]
Hi. I am sorry for my delayed response. I think I missed my notification. Allow me to address each of your questions.

1. Regarding the threshold 0.5
You are correct. Using only the maximum value would be more precise. In an earlier version of the project, the problem _was_ a multi-label classification, and it changed to a single-label classification in its later stage. I think I missed updating the thresholding function. Thank you for noticing it. Thankfully, the code should run fine even when the threshold is 0.5.

2. On replicating experiments
I ran the experiments in multiple Python versions. According to my experience, any version > 3.8 was fine. If you could tell me more details about the difficulties you are facing, I will try my best to help you out. 

Thank you for reaching out, and I apologize again for my delayed response.
